DELETE FROM teams

INSERT INTO teams(name) VALUES 
('Andy Zhen Forests'),
('Bennionville Bobcats'),
('Bentown Tippers'),
('Billings Enforcers'),
('Billville Jovyans'),
('Bjornstad Bears'),
('Byron Bay Headlands'),
('Chandler Bings'),
('Dayville Daytrippers'),
('Dahlberg Dall Sheep'),
('Grandberg Fir Peaks'),
('Florence Nightingales'),
('Gruberton Groupers'),
('Hughville Wagoneers'),
('Jacksonville Jackrabbits'),
('Jorlette Coordinators'),
('Knowlton Knolls'),
('Lawless Mappers'),
('Madsburg Avocados'),
('Marbraska Whitings'),
('Megtown Senders'),
('Mirandaville Mallards'),
('Motown Mosquedas'),
('Natesville Narwhals'),
('Pearsonville Felines'),
('Reynoldstown Wrappers'),
('Rylanta Falcons'),
('Rosieville Riveters'),
('Sudsville Swimmers'),
('Timtown Trekkers'),
('Victorville Vicars'),
('Wellsville Kakuros'),
('Worthenton Originals');