DELETE FROM teams

INSERT INTO teams(name) VALUES 
('Andy Zhen Forests'),
('Bennionville Bobcats'),
('Bentown Tippers'),
('Billings Enforcers'),
('Billville Jovyans'),
('Bjornstad Bears'),
('Byron Bay Bee-Eaters'),
('Chandler Bings'),
('Dayville Daytrippers'),
('Dahlberg Dall Sheep'),
('Grandberg Fir Peaks'),
('Florence Nightingales'),
('Gruberton Groupers'),
('Hughville Wagoneers'),
('Jacksonville Jackrabbits'),
('Jorlette Coordinators'),
('Knowlton Knolls'),
('Lawless Mappers'),
('Madsburg Avocados'),
('Marbraska Whitings'),
('Megtown Senders'),
('Mirandaville Mallards'),
('Motown Mosquedas'),
('Pearsonville Felines'),
('Reynoldstown Wrappers'),
('Rosieville Riveters'),
('Sudsville Swimmers'),
('Victorville Vicars'),
('Wellsville Kakuros'),
('Worthenton Originals');