DELETE FROM teams

INSERT INTO teams(name) VALUES 
('Andy Zhèn Forests'),
('Barangay Navio Biyolinistas'),
('Bennionville Bobcats'),
('Bentown Tippers'),
('Billings Enforcers'),
('Billville Jovyans'),
('Bjornstad Bears'),
('Bryton Headaches'),
('Chandler Bings'),
('Dayville Daytrippers'),
('Dahlberg Dall Sheep'),
('Grandberg Fir Peaks'),
('Florence Nightingales'),
('Gruberton Groupers'),
('Hughville Wagoneers'),
('Jorlette Coordinators'),
('Knowlton Knolls'),
('Lawless Mappers'),
('Mainekala Down Easters'),
('Marbraska Whitings'),
('Megtown Senders'),
('Mirandaville Mallards'),
('Pearsonville Felines'),
('Reynoldstown Wrappers'),
('Rosieville Riveters'),
('Sobczakgo Cubs'),
('Sudsville Swimmers'),
('Victorville Vicars'),
('Wellsville Kakuros'),
('Worthenton Originals');